#
# Copyright (c) 2017 Bitprim developers (see AUTHORS)
#
# This file is part of Bitprim.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+\.\d+$/
  
env:
   global:
     - CONAN_REFERENCE: "bitprim-rpc/0.6"
     - CONAN_USERNAME: "bitprim"
     - CONAN_LOGIN_USERNAME: "bitprim-bintray"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/bitprim/bitprim"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker

osx: &osx
   os: osx
   language: generic

matrix:
   include:
      - <<: *linux
        env: PUSH_TO_REPOS=true
   
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc72

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40

      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3

      # - <<: *osx
      #   osx_image: xcode8.2
      #   env: CONAN_APPLE_CLANG_VERSIONS=8.0

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1

install:
  - cd ${TRAVIS_BUILD_DIR}

  - |
    if [[ "${PUSH_TO_REPOS}" != "true" ]]; then
      chmod +x .travis/install.sh
      ./.travis/install.sh
    fi    

script:
  - git fetch --unshallow || true
  - export BITPRIM_BUILD_NUMBER="$(git describe)"
  - echo "${BITPRIM_BUILD_NUMBER}"

  - |
    if [[ "${PUSH_TO_REPOS}" == "true" ]]; then
      chmod +x .travis/push_other_repo.sh
      ./.travis/push_other_repo.sh
    else
      cd ${TRAVIS_BUILD_DIR}
      chmod +x .travis/run.sh
      ./.travis/run.sh
    fi  

notifications:
  email: false
  webhooks:
    urls: https://webhooks.gitter.im/e/a19dd2b03bf676d2b622
    on_success: change
    on_failure: always
